[package]
name = "locale1"
version = "0.1.0"
edition = "2024"

[dependencies]
zbus.workspace = true

[dev-dependencies]
futures = "0.3"
tokio = { version = "1", features = ["full"] }
zbus.workspace = true
zbus.features = ["tokio"]
