// SPDX-License-Identifier: MPL-2.0
//! # DBus interface proxy for: `org.freedesktop.NetworkManager.Device.Bluetooth`
//!
//! This code was generated by `zbus-xmlgen` `2.0.0` from DBus introspection data.
//! Source: `org.freedesktop.NetworkManager.Device.Bluetooth.xml`.
//!
//! You may prefer to adapt it, instead of using it verbatim.
//!
//! More information can be found in the
//! [Writing a client proxy](https://dbus.pages.freedesktop.org/zbus/client.html)
//! section of the zbus documentation.
//!

use zbus::proxy;

#[proxy(
	interface = "org.freedesktop.NetworkManager.Device.Bluetooth",
	default_service = "org.freedesktop.NetworkManager"
)]
pub trait BluetoothDevice {
	/// BtCapabilities property
	#[zbus(property)]
	fn bt_capabilities(&self) -> zbus::Result<u32>;

	/// HwAddress property
	#[zbus(property)]
	fn hw_address(&self) -> zbus::Result<String>;

	/// Name property
	#[zbus(property)]
	fn name(&self) -> zbus::Result<String>;
}
