// SPDX-License-Identifier: MPL-2.0
//! # DBus interface proxy for: `org.freedesktop.NetworkManager.Device.Tun`
//!
//! This code was generated by `zbus-xmlgen` `2.0.1` from DBus introspection data.
//! Source: `org.freedesktop.NetworkManager.Device.Tun.xml`.
//!
//! You may prefer to adapt it, instead of using it verbatim.
//!
//! More information can be found in the
//! [Writing a client proxy](https://dbus.pages.freedesktop.org/zbus/client.html)
//! section of the zbus documentation.
//!

use zbus::proxy;

#[proxy(
	interface = "org.freedesktop.NetworkManager.Device.Tun",
	default_service = "org.freedesktop.NetworkManager"
)]
pub trait TunDevice {
	/// Group property
	#[zbus(property)]
	fn group(&self) -> zbus::Result<i64>;

	/// HwAddress property
	#[zbus(property)]
	fn hw_address(&self) -> zbus::Result<String>;

	/// Mode property
	#[zbus(property)]
	fn mode(&self) -> zbus::Result<String>;

	/// MultiQueue property
	#[zbus(property)]
	fn multi_queue(&self) -> zbus::Result<bool>;

	/// NoPi property
	#[zbus(property)]
	fn no_pi(&self) -> zbus::Result<bool>;

	/// Owner property
	#[zbus(property)]
	fn owner(&self) -> zbus::Result<i64>;

	/// VnetHdr property
	#[zbus(property)]
	fn vnet_hdr(&self) -> zbus::Result<bool>;
}
