// SPDX-License-Identifier: MPL-2.0
//! # DBus interface proxy for: `org.freedesktop.NetworkManager.Device.WireGuard`
//!
//! This code was generated by `zbus-xmlgen` `2.0.1` from DBus introspection data.
//! Source: `org.freedesktop.NetworkManager.Device.WireGuard.xml`.
//!
//! You may prefer to adapt it, instead of using it verbatim.
//!
//! More information can be found in the
//! [Writing a client proxy](https://dbus.pages.freedesktop.org/zbus/client.html)
//! section of the zbus documentation.
//!

use zbus::proxy;

#[proxy(
	interface = "org.freedesktop.NetworkManager.Device.WireGuard",
	default_service = "org.freedesktop.NetworkManager"
)]
pub trait WireGuardDevice {
	/// FwMark property
	#[zbus(property)]
	fn fw_mark(&self) -> zbus::Result<u32>;

	/// ListenPort property
	#[zbus(property)]
	fn listen_port(&self) -> zbus::Result<u16>;

	/// PublicKey property
	#[zbus(property)]
	fn public_key(&self) -> zbus::Result<Vec<u8>>;
}
