//! # D-Bus interface proxy for: `org.freedesktop.NetworkManager.AgentManager`
//!
//! This code was generated by `zbus-xmlgen` `5.0.0` from D-Bus introspection data.
//! Source: `test.xml`.
//!
//! You may prefer to adapt it, instead of using it verbatim.
//!
//! More information can be found in the [Writing a client proxy] section of the zbus
//! documentation.
//!
//!
//! [Writing a client proxy]: https://dbus2.github.io/zbus/client.html
//! [D-Bus standard interfaces]: https://dbus.freedesktop.org/doc/dbus-specification.html#standard-interfaces,
use zbus::proxy;
#[proxy(
	interface = "org.freedesktop.NetworkManager.AgentManager",
	default_service = "org.freedesktop.NetworkManager",
	default_path = "/org/freedesktop/NetworkManager/AgentManager",
	assume_defaults = true
)]
pub trait AgentManager {
	/// Register method
	fn register(&self, identifier: &str) -> zbus::Result<()>;

	/// RegisterWithCapabilities method
	fn register_with_capabilities(&self, identifier: &str, capabilities: u32) -> zbus::Result<()>;

	/// Unregister method
	fn unregister(&self) -> zbus::Result<()>;
}
